services:
  tun2socks-wg:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
       - WG_HOST=${WG_HOST}
       - VLESS_IP=${VLESS_IP}
       - PASSWORD=${PASSWORD}
      volumes:
        - .:/etc/wireguard
      ports:
      - "51820:51820/udp"
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      sysctls:
        - net.ipv4.ip_forward=1
        - net.ipv4.conf.all.src_valid_mark=1
      devices:
        - /dev/net/tun
      restart: unless-stopped  
      networks:
        - t2s-wg
      depends_on:
        - xray
  xray:
    image: teddysun/xray
    container_name: xray
    volumes:
      - ./config.json:/etc/xray/config.json
    restart: unless-stopped
    networks:
      - t2s-wg
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - t2s-wg
    depends_on:
      - tun2socks-wg

volumes:
  caddy_data:
  caddy_config:

networks:
  t2s-wg:
    driver: bridge
